name: CD Pipeline

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Build Docker Image
        run: docker build -t gurkasathish/medusa-backend:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push gurkasathish/medusa-backend:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to ECS
        run: |
          # Register the new task definition
          aws ecs register-task-definition \
            --family medusa-task \
            --container-definitions '[{
              "name": "medusa-container",
              "image": "gurkasathish/medusa-backend:latest",
              "memory": 512,
              "cpu": 256,
              "essential": true,
              "portMappings": [{
                "containerPort": 80,
                "hostPort": 80
              }]
            }]' \
            --requires-compatibilities "FARGATE" \
            --network-mode "awsvpc" \
            --cpu "256" \
            --memory "512"
          
          # Update ECS service with the new task definition
          aws ecs update-service \
            --cluster medusa-cluster \
            --service medusa-service \
            --task-definition medusa-task
